<a href="https://colab.research.google.com/github/Afsheen36/OncoExtractAI-QA/blob/main/notebooks/OncoExtractAI_QA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import re
import os
import zipfile

print("OncoExtractAI-QA setup complete")

OncoExtractAI-QA setup complete

In [2]:
from google.colab import files

uploaded = files.upload()

Saving TCGA_Reports.csv.zip to TCGA_Reports.csv.zip

In [3]:
os.listdir()

['.config', 'TCGA_Reports.csv.zip', 'sample_data']

In [4]:
zip_path = "TCGA_Reports.csv.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("data")

os.listdir("data")

['TCGA_Reports.csv', '__MACOSX']

In [5]:
df = pd.read_csv("data/TCGA_Reports.csv")

df.head()

,patient_filename,text
0,TCGA-BP-5195.25c0b433-5557-4165-922e-2c1eac9c26f0,Date of Recelpt: Clinical Diagnosis & History:...
1,TCGA-D7-8573.b7306a47-697d-4ed3-bbe1-81d49674a8f8,"Material: 1) Material: stomach, Method of coll..."
2,TCGA-EI-7004.13591eed-30e5-47a3-91be-7a370663d2d4,page 1 / 1. copy No. 3. Examination: Histopath...
3,TCGA-EB-A82B.23E186C6-739C-4EF1-8788-79AA89C6E87A,Patient ID: Gross Description: A mass is locat...
4,TCGA-A6-3808.e1505f65-72ef-438d-a5e1-93ed8bf6635d,SPECIMEN. Right colon. CLINICAL NOTES. PRE-OP ...

In [6]:
df.shape

(9523, 2)

In [7]:
df.columns

Index(['patient_filename', 'text'], dtype='object')

In [8]:
lung_df = df[df["patient_filename"].str.contains("LUAD|LUSC", case=False, na=False)]

lung_df.shape

(0, 2)

In [9]:
lung_df = df[df["text"].str.contains("lung|pulmonary|bronchus|bronchial|lobe", case=False, na=False)]

lung_df.shape

(2416, 2)

In [10]:
print(lung_df.iloc[0]["text"][:2000])

FINAL DIAGNOSIS: PART 1: ESOPHAGUS, ESOPHAGECTOMY -. A. ADENOCARCINOMA, MODERATELY DIFFERENTIATED, SCM, INVASIVE INTO THE SUBMUCOSA (pT1b). B. NEGATIVE FOR ANGIOLYMPHATIC AND PERINEURAL INVASION. C. SURGICAL RESECTION MARGINS (PROXIMAL ESOPHAGUS, DISTAL STOMACH AND ADVENTITIAL MARGIN). ARE NEGATIVE FOR NEOPLASTIC INVOLVEMENT. D. THE TUMOR COMES WITHIN 0.2CM OF THE RADIAL/ADVENTITIAL SURGICAL RESECTION MARGIN. E. 1.6CM DISTALLY FROM THE MAIN TUMOR IS A 0.9CM FOCUS OF HIGH GRADE DYSPLASIA. F. BACKGROUND GASTROESOPHAGEAL MUCOSA WITH BARRETT'S MUCOSA. G. THERE IS NO EVIDENCE OF MALIGNANCY IN NINE LYMPH NODES (0/9). H. AJCC STAGING: pT1b NO. PART 2: LYMPH NODE, SUBCARINAL NEAR LEFT MAIN BRONCHUS, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 3: LYMPH NODE, SUBCARINAL NEAR RIGHT MAIN BRONCHUS, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 4: LYMPH NODE, SUBCARINAL NEAR PERICARDIUM, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 5: LYMPH NODE, SUBCARINAL NEAR THORACIC DUCT, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 6: LYMPH NODE, PARAESOPHAGEAL NEAR LEFT VEIN, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 7: LYMPH NODE, PARAESOPHAGEAL NEAR RIGHT CRUS, EXCISION -. A. FIBROADIPOSE TISSUE, NO LYMPH NODES IDENTIFIED. B. THERE IS NO EVIDENCE OF MALIGNANCY. PART 8: LYMPH NODE, NEAR VAGUS, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 9: LYMPH NODE, SUBCARINAL NEAR ATRIUM, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 10: LYMPH NODE, LESSER CURVE, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 11: LYMPH NODE, NEAR LEFT GASTRIC ARTERY, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 12: LYMPH NODE, GASTRIC FAT, EXCISION -. A. SKELETAL MUSCLE AND FIBROADIPOSE TISSUE, NO LYMPH NODE IDENTIFIED. B. THERE IS NO

In [11]:
lung_df = df[df["text"].str.contains("lung|pulmonary|bronchus|bronchial", case=False, na=False)]

lung_df.shape

(1074, 2)

In [12]:
print(lung_df.iloc[0]["text"][:2000])

FINAL DIAGNOSIS: PART 1: ESOPHAGUS, ESOPHAGECTOMY -. A. ADENOCARCINOMA, MODERATELY DIFFERENTIATED, SCM, INVASIVE INTO THE SUBMUCOSA (pT1b). B. NEGATIVE FOR ANGIOLYMPHATIC AND PERINEURAL INVASION. C. SURGICAL RESECTION MARGINS (PROXIMAL ESOPHAGUS, DISTAL STOMACH AND ADVENTITIAL MARGIN). ARE NEGATIVE FOR NEOPLASTIC INVOLVEMENT. D. THE TUMOR COMES WITHIN 0.2CM OF THE RADIAL/ADVENTITIAL SURGICAL RESECTION MARGIN. E. 1.6CM DISTALLY FROM THE MAIN TUMOR IS A 0.9CM FOCUS OF HIGH GRADE DYSPLASIA. F. BACKGROUND GASTROESOPHAGEAL MUCOSA WITH BARRETT'S MUCOSA. G. THERE IS NO EVIDENCE OF MALIGNANCY IN NINE LYMPH NODES (0/9). H. AJCC STAGING: pT1b NO. PART 2: LYMPH NODE, SUBCARINAL NEAR LEFT MAIN BRONCHUS, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 3: LYMPH NODE, SUBCARINAL NEAR RIGHT MAIN BRONCHUS, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 4: LYMPH NODE, SUBCARINAL NEAR PERICARDIUM, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 5: LYMPH NODE, SUBCARINAL NEAR THORACIC DUCT, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 6: LYMPH NODE, PARAESOPHAGEAL NEAR LEFT VEIN, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 7: LYMPH NODE, PARAESOPHAGEAL NEAR RIGHT CRUS, EXCISION -. A. FIBROADIPOSE TISSUE, NO LYMPH NODES IDENTIFIED. B. THERE IS NO EVIDENCE OF MALIGNANCY. PART 8: LYMPH NODE, NEAR VAGUS, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 9: LYMPH NODE, SUBCARINAL NEAR ATRIUM, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 10: LYMPH NODE, LESSER CURVE, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 11: LYMPH NODE, NEAR LEFT GASTRIC ARTERY, EXCISION -. THERE IS NO EVIDENCE OF MALIGNANCY IN ONE LYMPH NODE (0/1). PART 12: LYMPH NODE, GASTRIC FAT, EXCISION -. A. SKELETAL MUSCLE AND FIBROADIPOSE TISSUE, NO LYMPH NODE IDENTIFIED. B. THERE IS NO

In [13]:
lung_cancer_df = df[df["text"].str.contains("lung adenocarcinoma|pulmonary adenocarcinoma|lung squamous|squamous cell carcinoma of lung|non-small cell lung", case=False, na=False)]

lung_cancer_df.shape

(65, 2)

In [14]:
print(lung_cancer_df.iloc[0]["text"][:2000])

approved by the US Food and Drug Administration. The FDA has. determined that such clearance or approval is not necessary. This. test is used for clinical purposes. It should not be regarded as. investigational or for research. The laboratory is regulated under. the Clinical Laboratory Improvement Amendments of. (CLIA) as. qualified to perform high complexity clinical testing. Addendum #4 performed by. The electronic signature attests that the named Attending. Pathologist has evaluated the specimen referred to in the signed. section of the report and formulated the diagnosis therein. This report may include one or more immunohistochemical stain. results that use analyte specific reagents. The tests were developed and their performance characteristics. determined by. They have not been cleared or approved by the US Food and Drug. Administration. The FDA has determined that such clearance or approval is not. necessary. SPECIMENS: 1. F/S LUNG, LEFT UPPER LOBE WEDGE. 2. LEVEL 5 LYMPH NODE, LEFT. 3. COMPLETION LEFT UPPER LOBECTOMY. 4. LEVEL 9 LYMPH NODE. SEE ADDENDUM. Reason For Addendum #1: Molecular Studies. Reason For Addendum #2: Molecular Studies. Reason For Addendum #3: Molecular Studies. Reason For Addendum #4: Biomarker Report. DIAGNOSIS: 1,3. LUNG, LEFT UPPER LOBE: WEDGE RESECTION AND COMPLETION. LOBECTOMY. - ADENOCARCINOMA, SOLID PREDOMINANT (3.2 CM), SEE NOTE. - THE BRONCHIAL AND VASCULAR MARGINS ARE FREE OF TUMOR. SEVEN LYMPH NODES, NEGATIVE FOR CARCINOMA (0/7). Note: The tumor consists of solid (90%) and micropapillary (10%). components and measures 3.2 cm in greatest dimension. microscopically. Results of mutational studies will be reported in. addenda. 2. LYMPH NODE, LEVEL 5: BIOPSY. TWO LYMPH NODES, NEGATIVE FOR CARCINOMA (0/2). 4. LYMPH NODE, LEVEL 9: BIOPSY. TWO LYMPH NODES, NEGATIVE FOR CARCINOMA (0/2). Specimens: 1: F/S LUNG, LEFT UPPER LOBE WEDGE. 2: LEVEL 5 LYMPH NODE, LEFT. 3: COMPLETION LEFT UPPER LOBECTOMY. 4: LEVEL 9 LYMPH NODE. LUNG: Resection.

In [15]:
lung_cancer_df["patient_filename"].head(10)

129     TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f
379     TCGA-67-3772.1b3a5b8e-7469-4fd6-b314-ad1fd7a2b957
412     TCGA-50-6592.9a5098a9-7600-4b77-9b16-d6c274affd77
427     TCGA-55-8302.aa106e5a-b9b9-4f54-b902-120e8a3eb689
513     TCGA-50-5936.8d30d2aa-bef2-4329-944b-99ad5c9d8fc6
526     TCGA-91-6849.910d922e-8180-48ba-9e13-0f177dc71b2d
1113    TCGA-97-A4LX.1D7E3689-7B7F-4916-BCD9-04C5A98F09DE
1295    TCGA-34-2605.53291789-2743-4446-b859-aa65568586a7
1422    TCGA-97-A4M5.BD386F47-1CDC-46D5-A14D-F7D27F70982F
1656    TCGA-97-A4M2.0D5976EC-5D41-44A2-AC0A-CBE90F2A908E
Name: patient_filename, dtype: object

In [16]:
sample_df = lung_cancer_df.sample(30, random_state=42).reset_index(drop=True)

sample_df.shape

(30, 2)

In [17]:
label_template = sample_df[["patient_filename"]].copy()

label_template["histology_correct"] = ""
label_template["tumor_size_correct"] = ""
label_template["pT_correct"] = ""
label_template["pN_correct"] = ""
label_template["evidence_text"] = ""
label_template["notes"] = ""

label_template.head()

,patient_filename,histology_correct,tumor_size_correct,pT_correct,pN_correct,evidence_text,notes
0,TCGA-55-7913.7ce361fa-ad56-4e0e-95e3-ea977a513e98,,,,,,
1,TCGA-05-4389.924f5877-07dc-48dc-b920-c59ba743498e,,,,,,
2,TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f,,,,,,
3,TCGA-05-4245.902fe548-5b93-49c9-81db-2af4a4a88f3c,,,,,,
4,TCGA-91-6849.910d922e-8180-48ba-9e13-0f177dc71b2d,,,,,,

In [18]:
label_template.to_csv("lung_cancer_label_template.csv", index=False)

In [19]:
files.download("lung_cancer_label_template.csv")

In [20]:
sample_df.to_csv("lung_cancer_sample_reports.csv", index=False)
files.download("lung_cancer_sample_reports.csv")

In [21]:
sample_df.head(3)

,patient_filename,text
0,TCGA-55-7913.7ce361fa-ad56-4e0e-95e3-ea977a513e98,LUNG CANCER MUTATION PANEL. SPECIMEN SOURCE: L...
1,TCGA-05-4389.924f5877-07dc-48dc-b920-c59ba743498e,Mixed bronchopulmonary adenocarcinoma. Comment...
2,TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f,approved by the US Food and Drug Administratio...

In [22]:
print(sample_df.iloc[1]["text"])

Mixed bronchopulmonary adenocarcinoma. Comment/supplementary remark: histoarchitecture and cell morphology of the tumor are. consistent with a bronchopulmonary origin of the tumor. This will be reviewed and confirmed. in immunohistological investigations. The tumor is completely removed by wedge excision of. sample 1.). The visceral pleura, the right upper lobe of sample 2.), including its resection. margin of the bronchus and vessels and all the lymph nodes removed are tumor-free. On the. assumption of a bronchopulmonary origin to the tumor: Tumor classification: pT1, pNo, R0,. stage IA. C 34.1 M 8255/3.

In [23]:
def extract_histology(text):
    text_lower = str(text).lower()

    if "adenocarcinoma" in text_lower:
        return "adenocarcinoma"
    elif "squamous cell carcinoma" in text_lower:
        return "squamous cell carcinoma"
    elif "non-small cell" in text_lower:
        return "non-small cell lung cancer"
    else:
        return "not found"

sample_df["histology_extracted"] = sample_df["text"].apply(extract_histology)

sample_df[["patient_filename", "histology_extracted"]].head()

                                    patient_filename histology_extracted
0  TCGA-55-7913.7ce361fa-ad56-4e0e-95e3-ea977a513e98      adenocarcinoma
1  TCGA-05-4389.924f5877-07dc-48dc-b920-c59ba743498e      adenocarcinoma
2  TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f      adenocarcinoma
3  TCGA-05-4245.902fe548-5b93-49c9-81db-2af4a4a88f3c      adenocarcinoma
4  TCGA-91-6849.910d922e-8180-48ba-9e13-0f177dc71b2d      adenocarcinoma

In [24]:
def extract_tumor_size(text):
    pattern = r'(\d+(\.\d+)?)\s*cm'
    match = re.search(pattern, str(text), re.IGNORECASE)

    if match:
        return match.group(0)
    else:
        return "not found"

sample_df["tumor_size_extracted"] = sample_df["text"].apply(extract_tumor_size)

sample_df[["patient_filename", "histology_extracted", "tumor_size_extracted"]].head()

,patient_filename,histology_extracted,tumor_size_extracted
0,TCGA-55-7913.7ce361fa-ad56-4e0e-95e3-ea977a513e98,adenocarcinoma,2.4 cm
1,TCGA-05-4389.924f5877-07dc-48dc-b920-c59ba743498e,adenocarcinoma,not found
2,TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f,adenocarcinoma,3.2 CM
3,TCGA-05-4245.902fe548-5b93-49c9-81db-2af4a4a88f3c,adenocarcinoma,3.2 cm
4,TCGA-91-6849.910d922e-8180-48ba-9e13-0f177dc71b2d,adenocarcinoma,0.4 cm

In [25]:
def extract_pT(text):
    pattern = r'\bpT[0-4][a-d]?\b'
    match = re.search(pattern, str(text), re.IGNORECASE)

    if match:
        return match.group(0)
    else:
        return "not found"

sample_df["pT_extracted"] = sample_df["text"].apply(extract_pT)

sample_df[["patient_filename", "histology_extracted", "tumor_size_extracted", "pT_extracted"]].head()

,patient_filename,histology_extracted,tumor_size_extracted,pT_extracted
0,TCGA-55-7913.7ce361fa-ad56-4e0e-95e3-ea977a513e98,adenocarcinoma,2.4 cm,pT1b
1,TCGA-05-4389.924f5877-07dc-48dc-b920-c59ba743498e,adenocarcinoma,not found,pT1
2,TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f,adenocarcinoma,3.2 CM,pT2a
3,TCGA-05-4245.902fe548-5b93-49c9-81db-2af4a4a88f3c,adenocarcinoma,3.2 cm,not found
4,TCGA-91-6849.910d922e-8180-48ba-9e13-0f177dc71b2d,adenocarcinoma,0.4 cm,not found

In [26]:
def extract_pN(text):
    pattern = r'\bpN[0-3xX][a-d]?\b'
    match = re.search(pattern, str(text), re.IGNORECASE)

    if match:
        return match.group(0)
    else:
        return "not found"

sample_df["pN_extracted"] = sample_df["text"].apply(extract_pN)

sample_df[["patient_filename", "histology_extracted", "tumor_size_extracted", "pT_extracted", "pN_extracted"]].head()

,patient_filename,histology_extracted,tumor_size_extracted,pT_extracted,pN_extracted
0,TCGA-55-7913.7ce361fa-ad56-4e0e-95e3-ea977a513e98,adenocarcinoma,2.4 cm,pT1b,not found
1,TCGA-05-4389.924f5877-07dc-48dc-b920-c59ba743498e,adenocarcinoma,not found,pT1,not found
2,TCGA-97-8175.19c71bba-794d-4245-bbd8-536740912c9f,adenocarcinoma,3.2 CM,pT2a,pN0
3,TCGA-05-4245.902fe548-5b93-49c9-81db-2af4a4a88f3c,adenocarcinoma,3.2 cm,not found,not found
4,TCGA-91-6849.910d922e-8180-48ba-9e13-0f177dc71b2d,adenocarcinoma,0.4 cm,not found,not found

In [27]:
sample_df.to_csv("basic_extraction_results.csv", index=False)
label_template.to_csv("lung_cancer_label_template.csv", index=False)

In [28]:
files.download("basic_extraction_results.csv")
files.download("lung_cancer_label_template.csv")
files.download("lung_cancer_sample_reports.csv")